all: hereroNamaPrisoners.jpg africa.png brasil1986.jpg brasil2020.jpg

africa.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/africa.png

hereroNamaPrisoners.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/hereroNamaPrisoners.jpg

brasil1986.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/brasil1986.jpg

brasil2020.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/brasil2020.jpg
