all:
	echo "Leer el makefile"

archivos:
	wget "https://www.argentina.gob.ar/sites/default/files/2020/07/1_-_preguntas_frecuentes_edc_para_municipios.pdf"
	wget "https://www.argentina.gob.ar/sites/default/files/2020/07/2-_reglamento_operativo_programa_de_capacitacion_4.0_y_economia_del_conocimiento.pdf"
	wget "https://www.argentina.gob.ar/sites/default/files/2020/07/3_-_instructivo_formulario_a_para_ingresar_proyectos_en_tad.pdf"
	wget "https://www.argentina.gob.ar/sites/default/files/2020/07/4_-_modelo_formulario_a_descripcion_del_proyecto.docx"
	wget "https://www.argentina.gob.ar/sites/default/files/2020/07/5_-_modelo_programa_de_curso.docx"
	wget "https://www.argentina.gob.ar/sites/default/files/2020/07/6_-_modelo_de_presupuesto.xlsx"
	
	
