#ffmpeg -i clase1.mp4 -ss 00:00:00 -t 00:21:00 -vcodec copy -acodec copy clase1_0.mp4
#ffmpeg -i clase1.mp4 -ss 00:21:00 -t 00:21:00 -vcodec copy -acodec copy clase1_1.mp4
#ffmpeg -i clase1.mp4 -ss 00:42:00 -t 00:21:00 -vcodec copy -acodec copy clase1_2.mp4

download:
	wget https://github.com/glandfried/bayesian-inference/releases/download/v2020.1.1/clase1_0.mp4
	wget https://github.com/glandfried/bayesian-inference/releases/download/v2020.1.1/clase1_1.mp4
	wget https://github.com/glandfried/bayesian-inference/releases/download/v2020.1.1/clase1_2.mp4
